#include <iostream.h>
#include <conio.h>
#include <dos.h>
#include <stdio.h>
void main(){

int N=0;

clrscr();

cprintf("\n Pressione qualquer tecla.");
cscanf("%c");
sound(494);
delay(200);
nosound();
delay(100);

sound(494);
delay(200);
nosound();
delay(100);

sound(494);
delay(500);
nosound();
delay(100);

sound(494);
delay(200);
nosound();
delay(100);

sound(494);
delay(200);
nosound();
delay(100);

sound(494);
delay(500);
nosound();
delay(100);

sound(494);
delay(200);
nosound();
delay(100);

sound(587);
delay(200);
nosound();
delay(100);

sound(392);
delay(200);
nosound();
delay(100);

sound(440);
delay(200);
nosound();
delay(100);

sound(494);
delay(1000);
nosound();
delay(100);

sound(523);
delay(200);
nosound();
delay(100);

sound(523);
delay(200);
nosound();
delay(100);

sound(523);
delay(500);
nosound();
delay(100);

sound(494);
delay(200);
nosound();
delay(100);

sound(494);
delay(200);
nosound();
delay(100);

sound(494);
delay(500);
nosound();
delay(100);

sound(440);
delay(200);
nosound();
delay(100);

sound(494);
delay(200);
nosound();
delay(100);

sound(440);
delay(200);
nosound();
delay(100);

sound(494);
delay(200);
nosound();
delay(100);

sound(440);
delay(500);
nosound();
delay(100);

sound(587);
delay(500);
nosound();
delay(100);

getch();

}