//Kirby.Cpp

#include <iostream.h>
#include <conio.h>
#include <dos.h>

void main(){

int i;

for(i=1; i<10; i++){
clrscr();
cout<<"\n <('o' <)";
delay(80);
clrscr();
cout<<"\n ^( '-' )^";
delay(80);
clrscr();
cout<<"\n  (>'o' )>";
delay(80);
clrscr();
cout<<"\n v( '.' )v";
delay(80);
clrscr();
cout<<"\n <(' .' )>";
delay(80);
clrscr();
cout<<"\n <('.' <)";
delay(80);
clrscr();
cout<<"\n ^( '.' )^";
delay(80);
clrscr();
cout<<"\n  (>'.' )>";
delay(80);
clrscr();
cout<<"\n v( '.' )v";
delay(80);
clrscr();
cout<<"\n <(' .' )>";
delay(80);


}

cout<<"\n Pressione qualquer tecla para continuar.";
getch();
}