#include <conio.h>
#include <dos.h>
#include <stdio.h>
void main(){

clrscr();

printf("\n Pressione qualquer tecla.");
scanf("%c");
//Yohohoho Pt1:
sound(392);
delay(100);
nosound();
delay(100);

sound(466);
delay(100);
nosound();
delay(100);

sound(466);
delay(100);
nosound();
delay(100);

sound(466);
delay(1000);
nosound();
delay(100);


sound(523);
delay(300);
nosound();
delay(100);

sound(466);
delay(100);
nosound();
delay(100);

sound(392);
delay(500);
nosound();
delay(100);

sound(466);
delay(1000);
nosound();
delay(500);

//Yohohoho Pt2:
sound(392);
delay(100);
nosound();
delay(100);

sound(466);
delay(100);
nosound();
delay(100);

sound(466);
delay(100);
nosound();
delay(100);

sound(466);
delay(1000);
nosound();
delay(100);


sound(523);
delay(300);
nosound();
delay(100);

sound(466);
delay(100);
nosound();
delay(100);

sound(392);
delay(500);
nosound();
delay(100);

sound(311);
delay(1000);
nosound();
delay(500);

//Binkusu Pt1:
sound(466);
delay(300);
nosound();
delay(100);

sound(392);
delay(100);
nosound();
delay(100);

sound(349);
delay(300);
nosound();
delay(100);

sound(311);
delay(100);
nosound();
delay(100);

sound(262);
delay(300);
nosound();
delay(100);

sound(294);
delay(100);
nosound();
delay(100);

sound(311);
delay(500);
nosound();
delay(100);


sound(466);
delay(300);
nosound();
delay(100);

sound(392);
delay(100);
nosound();
delay(100);

sound(349);
delay(300);
nosound();
delay(100);

sound(311);
delay(100);
nosound();
delay(100);

sound(262);
delay(300);
nosound();
delay(100);

sound(311);
delay(100);
nosound();
delay(100);

sound(233);
delay(500);
nosound();
delay(100);


sound(262);
delay(300);
nosound();
delay(100);

sound(311);
delay(100);
nosound();
delay(100);

sound(233);
delay(300);
nosound();
delay(100);

sound(233);
delay(100);
nosound();
delay(100);

sound(262);
delay(300);
nosound();
delay(100);

sound(311);
delay(100);
nosound();
delay(100);

sound(233);
delay(300);
nosound();
delay(100);

sound(233);
delay(100);
nosound();
delay(100);

sound(262);
delay(300);
nosound();
delay(100);

sound(294);
delay(100);
nosound();
delay(100);

sound(311);
delay(300);
nosound();
delay(100);

sound(415);
delay(100);
nosound();
delay(100);

sound(392);
delay(300);
nosound();
delay(100);

sound(392);
delay(100);
nosound();
delay(100);

sound(349);
delay(300);
nosound();
delay(100);

sound(311);
delay(100);
nosound();
delay(100);

sound(349);
delay(500);
nosound();
delay(300);

sound(466);
delay(300);
nosound();
delay(300);

//Binkusu Pt2:
sound(466);
delay(300);
nosound();
delay(100);

sound(392);
delay(100);
nosound();
delay(100);

sound(349);
delay(300);
nosound();
delay(100);

sound(311);
delay(100);
nosound();
delay(100);

sound(262);
delay(300);
nosound();
delay(100);

sound(294);
delay(100);
nosound();
delay(100);

sound(311);
delay(500);
nosound();
delay(100);


sound(466);
delay(300);
nosound();
delay(100);

sound(392);
delay(100);
nosound();
delay(100);

sound(349);
delay(300);
nosound();
delay(100);

sound(311);
delay(100);
nosound();
delay(100);

sound(262);
delay(300);
nosound();
delay(100);

sound(311);
delay(100);
nosound();
delay(100);

sound(233);
delay(500);
nosound();
delay(100);


sound(262);
delay(300);
nosound();
delay(100);

sound(311);
delay(100);
nosound();
delay(100);

sound(233);
delay(300);
nosound();
delay(100);

sound(233);
delay(100);
nosound();
delay(100);

sound(262);
delay(300);
nosound();
delay(100);

sound(311);
delay(100);
nosound();
delay(100);

sound(233);
delay(300);
nosound();
delay(100);

sound(233);
delay(100);
nosound();
delay(100);

sound(262);
delay(300);
nosound();
delay(100);

sound(294);
delay(100);
nosound();
delay(100);

sound(311);
delay(300);
nosound();
delay(100);

sound(415);
delay(100);
nosound();
delay(100);

sound(392);
delay(300);
nosound();
delay(100);

sound(392);
delay(100);
nosound();
delay(100);

sound(349);
delay(300);
nosound();
delay(100);

sound(349);
delay(100);
nosound();
delay(100);

sound(311);
delay(1000);
nosound();
delay(100);

getch();
}